name: library

services:
  if_lib_db:
    image: postgres:17.3-bookworm
    restart: always
    container_name: cf_lib_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./administer/psql:/docker-entrypoint-initdb.d
    env_file:
      - .env

  if_lib_redis:
    image: redis:7.2.4-bookworm
    restart: always
    container_name: cf_lib_redis

  if_lib_celery: &if_lib_celery
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PC_USER: ${PC_USER}
    command: ["./administer/runner.sh", "celery"]
    restart: always
    container_name: cf_lib_celery
    volumes:
      - .:/code
    env_file:
      - .env

  if_lib_beats:
    <<: *if_lib_celery
    command: ["./administer/runner.sh", "beat"]
    restart: always
    container_name: cf_lib_beats

  if_lib_web:
    <<: *if_lib_celery
    command: ["./administer/web.sh"]
    restart: always
    container_name: cf_lib_web
    ports:
      - "8000:80"

volumes:
  postgres_data:
